table EmployeeDetails
	lineageTag: e3cbb1b8-918c-4509-9c7b-2902fccd97fb

	column Id
		dataType: int64
		formatString: 0
		lineageTag: eb8d847e-9e79-4179-9163-1744fd132849
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7f2c1fbc-f35d-4251-8a5a-1b83ea7542a8
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition EmployeeDetails = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\01- Documents\29-11- PowerBI\000 CRM\sampleData_xviz.xlsx"), null, true),
				    EmployeeDetails_Sheet = Source{[Item="EmployeeDetails",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(EmployeeDetails_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Id", Int64.Type}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

